name: Merge-Tests
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KEY_HEADER: "X-API-KEY: ${{secrets.API-KEY}}"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Reflect tests
        run: curl
             -X POST
             -H "$KEY_HEADER
             -s https://api.reflect.run/v1/suites/Sample/executions
